# -*- coding: utf-8 -*-
"""my_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dkt38WjfNbW5A4kLpZD9pnJhNcqTFvbw
"""

import numpy as np

def gen_random():
  return np.random.random()

def greet(name):
  """
  This function takes a name as input and returns a greeting message.
  """
  return f"Hello, {name}! Welcome to my module."

def add_numbers(a, b):
  """
  Add two numbers and return the result
  """
  return a + b

def multiply_numbers(a, b):
  """
  Multiply two numbers and return the result
  """
  return a * b